/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.OdsApi.Sdk.v54.Client.OpenAPIDateConverter;

namespace EdFi.OdsApi.Sdk.v54.Models.All
{
    /// <summary>
    /// EdFiSection
    /// </summary>
    [DataContract(Name = "edFi_section")]
    public partial class EdFiSection : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiSection" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdFiSection() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiSection" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="sectionIdentifier">The local identifier assigned to a section. (required).</param>
        /// <param name="courseOfferingReference">courseOfferingReference (required).</param>
        /// <param name="locationReference">locationReference.</param>
        /// <param name="locationSchoolReference">locationSchoolReference.</param>
        /// <param name="availableCreditConversion">Conversion factor that when multiplied by the number of credits is equivalent to Carnegie units..</param>
        /// <param name="availableCredits">The value of credits or units of value awarded for the completion of a course..</param>
        /// <param name="availableCreditTypeDescriptor">The type of credits or units of value awarded for the completion of a course..</param>
        /// <param name="characteristics">An unordered collection of sectionCharacteristics. Reflects important characteristics of the Section, such as whether or not attendance is taken and the Section is graded..</param>
        /// <param name="classPeriods">An unordered collection of sectionClassPeriods. The class period during which the Section meets..</param>
        /// <param name="courseLevelCharacteristics">An unordered collection of sectionCourseLevelCharacteristics. The type of specific program or designation with which the section is associated (e.g., AP, IB, Dual Credit, CTE). This collection should only be populated if it differs from the Course Level Characteristics identified at the Course Offering level..</param>
        /// <param name="educationalEnvironmentDescriptor">The setting in which a child receives education and related services; for example:        Center-based instruction        Home-based instruction        Hospital class        Mainstream        Residential care and treatment facility        ....</param>
        /// <param name="instructionLanguageDescriptor">The primary language of instruction, if omitted English is assumed..</param>
        /// <param name="mediumOfInstructionDescriptor">The media through which teachers provide instruction to students and students and teachers communicate about instructional matters; for example:        Technology-based instruction in classroom        Correspondence instruction        Face-to-face instruction        Virtual/On-line Distance learning        Center-based instruction        ....</param>
        /// <param name="offeredGradeLevels">An unordered collection of sectionOfferedGradeLevels. The grade levels in which the section is offered. This collection should only be populated if it differs from the Offered Grade Levels identified at the Course Offering level..</param>
        /// <param name="officialAttendancePeriod">Indicator of whether this section is used for official daily attendance. Alternatively, official daily attendance may be tied to a Class Period..</param>
        /// <param name="populationServedDescriptor">The type of students the Section is offered and tailored to; for example:        Bilingual students        Remedial education students        Gifted and talented students        Career and Technical Education students        Special education students        ....</param>
        /// <param name="programs">An unordered collection of sectionPrograms. Optional reference to program (e.g., CTE) to which the Section is associated..</param>
        /// <param name="sectionName">A locally-defined name for the section, generally created to make the section more recognizable in informal contexts and generally distinct from the SectionIdentifier..</param>
        /// <param name="sequenceOfCourse">When a section is part of a sequence of parts for a course, the number of the sequence. If the course has only one part, the value of this section attribute should be 1..</param>
        /// <param name="etag">A unique system-generated value that identifies the version of the resource..</param>
        /// <param name="ext">Extensions to the Section entity..</param>
        public EdFiSection(string id = default, string sectionIdentifier = default, EdFiCourseOfferingReference courseOfferingReference = default, EdFiLocationReference locationReference = default, EdFiSchoolReference locationSchoolReference = default, double availableCreditConversion = default, double availableCredits = default, string availableCreditTypeDescriptor = default, List<EdFiSectionCharacteristic> characteristics = default, List<EdFiSectionClassPeriod> classPeriods = default, List<EdFiSectionCourseLevelCharacteristic> courseLevelCharacteristics = default, string educationalEnvironmentDescriptor = default, string instructionLanguageDescriptor = default, string mediumOfInstructionDescriptor = default, List<EdFiSectionOfferedGradeLevel> offeredGradeLevels = default, bool officialAttendancePeriod = default, string populationServedDescriptor = default, List<EdFiSectionProgram> programs = default, string sectionName = default, int sequenceOfCourse = default, string etag = default, Object ext = default)
        {
            // to ensure "sectionIdentifier" is required (not null)
            if (sectionIdentifier == null)
            {
                throw new ArgumentNullException("sectionIdentifier is a required property for EdFiSection and cannot be null");
            }
            this.SectionIdentifier = sectionIdentifier;
            // to ensure "courseOfferingReference" is required (not null)
            if (courseOfferingReference == null)
            {
                throw new ArgumentNullException("courseOfferingReference is a required property for EdFiSection and cannot be null");
            }
            this.CourseOfferingReference = courseOfferingReference;
            this.Id = id;
            this.LocationReference = locationReference;
            this.LocationSchoolReference = locationSchoolReference;
            this.AvailableCreditConversion = availableCreditConversion;
            this.AvailableCredits = availableCredits;
            this.AvailableCreditTypeDescriptor = availableCreditTypeDescriptor;
            this.Characteristics = characteristics;
            this.ClassPeriods = classPeriods;
            this.CourseLevelCharacteristics = courseLevelCharacteristics;
            this.EducationalEnvironmentDescriptor = educationalEnvironmentDescriptor;
            this.InstructionLanguageDescriptor = instructionLanguageDescriptor;
            this.MediumOfInstructionDescriptor = mediumOfInstructionDescriptor;
            this.OfferedGradeLevels = offeredGradeLevels;
            this.OfficialAttendancePeriod = officialAttendancePeriod;
            this.PopulationServedDescriptor = populationServedDescriptor;
            this.Programs = programs;
            this.SectionName = sectionName;
            this.SequenceOfCourse = sequenceOfCourse;
            this.Etag = etag;
            this.Ext = ext;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// The local identifier assigned to a section.
        /// </summary>
        /// <value>The local identifier assigned to a section.</value>
        [DataMember(Name = "sectionIdentifier", IsRequired = true, EmitDefaultValue = true)]
        public string SectionIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets CourseOfferingReference
        /// </summary>
        [DataMember(Name = "courseOfferingReference", IsRequired = true, EmitDefaultValue = true)]
        public EdFiCourseOfferingReference CourseOfferingReference { get; set; }

        /// <summary>
        /// Gets or Sets LocationReference
        /// </summary>
        [DataMember(Name = "locationReference", EmitDefaultValue = false)]
        public EdFiLocationReference LocationReference { get; set; }

        /// <summary>
        /// Gets or Sets LocationSchoolReference
        /// </summary>
        [DataMember(Name = "locationSchoolReference", EmitDefaultValue = false)]
        public EdFiSchoolReference LocationSchoolReference { get; set; }

        /// <summary>
        /// Conversion factor that when multiplied by the number of credits is equivalent to Carnegie units.
        /// </summary>
        /// <value>Conversion factor that when multiplied by the number of credits is equivalent to Carnegie units.</value>
        [DataMember(Name = "availableCreditConversion", EmitDefaultValue = false)]
        public double AvailableCreditConversion { get; set; }

        /// <summary>
        /// The value of credits or units of value awarded for the completion of a course.
        /// </summary>
        /// <value>The value of credits or units of value awarded for the completion of a course.</value>
        [DataMember(Name = "availableCredits", EmitDefaultValue = false)]
        public double AvailableCredits { get; set; }

        /// <summary>
        /// The type of credits or units of value awarded for the completion of a course.
        /// </summary>
        /// <value>The type of credits or units of value awarded for the completion of a course.</value>
        [DataMember(Name = "availableCreditTypeDescriptor", EmitDefaultValue = false)]
        public string AvailableCreditTypeDescriptor { get; set; }

        /// <summary>
        /// An unordered collection of sectionCharacteristics. Reflects important characteristics of the Section, such as whether or not attendance is taken and the Section is graded.
        /// </summary>
        /// <value>An unordered collection of sectionCharacteristics. Reflects important characteristics of the Section, such as whether or not attendance is taken and the Section is graded.</value>
        [DataMember(Name = "characteristics", EmitDefaultValue = false)]
        public List<EdFiSectionCharacteristic> Characteristics { get; set; }

        /// <summary>
        /// An unordered collection of sectionClassPeriods. The class period during which the Section meets.
        /// </summary>
        /// <value>An unordered collection of sectionClassPeriods. The class period during which the Section meets.</value>
        [DataMember(Name = "classPeriods", EmitDefaultValue = false)]
        public List<EdFiSectionClassPeriod> ClassPeriods { get; set; }

        /// <summary>
        /// An unordered collection of sectionCourseLevelCharacteristics. The type of specific program or designation with which the section is associated (e.g., AP, IB, Dual Credit, CTE). This collection should only be populated if it differs from the Course Level Characteristics identified at the Course Offering level.
        /// </summary>
        /// <value>An unordered collection of sectionCourseLevelCharacteristics. The type of specific program or designation with which the section is associated (e.g., AP, IB, Dual Credit, CTE). This collection should only be populated if it differs from the Course Level Characteristics identified at the Course Offering level.</value>
        [DataMember(Name = "courseLevelCharacteristics", EmitDefaultValue = false)]
        public List<EdFiSectionCourseLevelCharacteristic> CourseLevelCharacteristics { get; set; }

        /// <summary>
        /// The setting in which a child receives education and related services; for example:        Center-based instruction        Home-based instruction        Hospital class        Mainstream        Residential care and treatment facility        ...
        /// </summary>
        /// <value>The setting in which a child receives education and related services; for example:        Center-based instruction        Home-based instruction        Hospital class        Mainstream        Residential care and treatment facility        ...</value>
        [DataMember(Name = "educationalEnvironmentDescriptor", EmitDefaultValue = false)]
        public string EducationalEnvironmentDescriptor { get; set; }

        /// <summary>
        /// The primary language of instruction, if omitted English is assumed.
        /// </summary>
        /// <value>The primary language of instruction, if omitted English is assumed.</value>
        [DataMember(Name = "instructionLanguageDescriptor", EmitDefaultValue = false)]
        public string InstructionLanguageDescriptor { get; set; }

        /// <summary>
        /// The media through which teachers provide instruction to students and students and teachers communicate about instructional matters; for example:        Technology-based instruction in classroom        Correspondence instruction        Face-to-face instruction        Virtual/On-line Distance learning        Center-based instruction        ...
        /// </summary>
        /// <value>The media through which teachers provide instruction to students and students and teachers communicate about instructional matters; for example:        Technology-based instruction in classroom        Correspondence instruction        Face-to-face instruction        Virtual/On-line Distance learning        Center-based instruction        ...</value>
        [DataMember(Name = "mediumOfInstructionDescriptor", EmitDefaultValue = false)]
        public string MediumOfInstructionDescriptor { get; set; }

        /// <summary>
        /// An unordered collection of sectionOfferedGradeLevels. The grade levels in which the section is offered. This collection should only be populated if it differs from the Offered Grade Levels identified at the Course Offering level.
        /// </summary>
        /// <value>An unordered collection of sectionOfferedGradeLevels. The grade levels in which the section is offered. This collection should only be populated if it differs from the Offered Grade Levels identified at the Course Offering level.</value>
        [DataMember(Name = "offeredGradeLevels", EmitDefaultValue = false)]
        public List<EdFiSectionOfferedGradeLevel> OfferedGradeLevels { get; set; }

        /// <summary>
        /// Indicator of whether this section is used for official daily attendance. Alternatively, official daily attendance may be tied to a Class Period.
        /// </summary>
        /// <value>Indicator of whether this section is used for official daily attendance. Alternatively, official daily attendance may be tied to a Class Period.</value>
        [DataMember(Name = "officialAttendancePeriod", EmitDefaultValue = true)]
        public bool OfficialAttendancePeriod { get; set; }

        /// <summary>
        /// The type of students the Section is offered and tailored to; for example:        Bilingual students        Remedial education students        Gifted and talented students        Career and Technical Education students        Special education students        ...
        /// </summary>
        /// <value>The type of students the Section is offered and tailored to; for example:        Bilingual students        Remedial education students        Gifted and talented students        Career and Technical Education students        Special education students        ...</value>
        [DataMember(Name = "populationServedDescriptor", EmitDefaultValue = false)]
        public string PopulationServedDescriptor { get; set; }

        /// <summary>
        /// An unordered collection of sectionPrograms. Optional reference to program (e.g., CTE) to which the Section is associated.
        /// </summary>
        /// <value>An unordered collection of sectionPrograms. Optional reference to program (e.g., CTE) to which the Section is associated.</value>
        [DataMember(Name = "programs", EmitDefaultValue = false)]
        public List<EdFiSectionProgram> Programs { get; set; }

        /// <summary>
        /// A locally-defined name for the section, generally created to make the section more recognizable in informal contexts and generally distinct from the SectionIdentifier.
        /// </summary>
        /// <value>A locally-defined name for the section, generally created to make the section more recognizable in informal contexts and generally distinct from the SectionIdentifier.</value>
        [DataMember(Name = "sectionName", EmitDefaultValue = false)]
        public string SectionName { get; set; }

        /// <summary>
        /// When a section is part of a sequence of parts for a course, the number of the sequence. If the course has only one part, the value of this section attribute should be 1.
        /// </summary>
        /// <value>When a section is part of a sequence of parts for a course, the number of the sequence. If the course has only one part, the value of this section attribute should be 1.</value>
        [DataMember(Name = "sequenceOfCourse", EmitDefaultValue = false)]
        public int SequenceOfCourse { get; set; }

        /// <summary>
        /// A unique system-generated value that identifies the version of the resource.
        /// </summary>
        /// <value>A unique system-generated value that identifies the version of the resource.</value>
        [DataMember(Name = "_etag", EmitDefaultValue = false)]
        public string Etag { get; set; }

        /// <summary>
        /// Extensions to the Section entity.
        /// </summary>
        /// <value>Extensions to the Section entity.</value>
        [DataMember(Name = "_ext", EmitDefaultValue = false)]
        public Object Ext { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiSection {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  SectionIdentifier: ").Append(SectionIdentifier).Append("\n");
            sb.Append("  CourseOfferingReference: ").Append(CourseOfferingReference).Append("\n");
            sb.Append("  LocationReference: ").Append(LocationReference).Append("\n");
            sb.Append("  LocationSchoolReference: ").Append(LocationSchoolReference).Append("\n");
            sb.Append("  AvailableCreditConversion: ").Append(AvailableCreditConversion).Append("\n");
            sb.Append("  AvailableCredits: ").Append(AvailableCredits).Append("\n");
            sb.Append("  AvailableCreditTypeDescriptor: ").Append(AvailableCreditTypeDescriptor).Append("\n");
            sb.Append("  Characteristics: ").Append(Characteristics).Append("\n");
            sb.Append("  ClassPeriods: ").Append(ClassPeriods).Append("\n");
            sb.Append("  CourseLevelCharacteristics: ").Append(CourseLevelCharacteristics).Append("\n");
            sb.Append("  EducationalEnvironmentDescriptor: ").Append(EducationalEnvironmentDescriptor).Append("\n");
            sb.Append("  InstructionLanguageDescriptor: ").Append(InstructionLanguageDescriptor).Append("\n");
            sb.Append("  MediumOfInstructionDescriptor: ").Append(MediumOfInstructionDescriptor).Append("\n");
            sb.Append("  OfferedGradeLevels: ").Append(OfferedGradeLevels).Append("\n");
            sb.Append("  OfficialAttendancePeriod: ").Append(OfficialAttendancePeriod).Append("\n");
            sb.Append("  PopulationServedDescriptor: ").Append(PopulationServedDescriptor).Append("\n");
            sb.Append("  Programs: ").Append(Programs).Append("\n");
            sb.Append("  SectionName: ").Append(SectionName).Append("\n");
            sb.Append("  SequenceOfCourse: ").Append(SequenceOfCourse).Append("\n");
            sb.Append("  Etag: ").Append(Etag).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SectionIdentifier (string) maxLength
            if (this.SectionIdentifier != null && this.SectionIdentifier.Length > 255)
            {
                yield return new ValidationResult("Invalid value for SectionIdentifier, length must be less than 255.", new [] { "SectionIdentifier" });
            }

            // AvailableCreditTypeDescriptor (string) maxLength
            if (this.AvailableCreditTypeDescriptor != null && this.AvailableCreditTypeDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for AvailableCreditTypeDescriptor, length must be less than 306.", new [] { "AvailableCreditTypeDescriptor" });
            }

            // EducationalEnvironmentDescriptor (string) maxLength
            if (this.EducationalEnvironmentDescriptor != null && this.EducationalEnvironmentDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for EducationalEnvironmentDescriptor, length must be less than 306.", new [] { "EducationalEnvironmentDescriptor" });
            }

            // InstructionLanguageDescriptor (string) maxLength
            if (this.InstructionLanguageDescriptor != null && this.InstructionLanguageDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for InstructionLanguageDescriptor, length must be less than 306.", new [] { "InstructionLanguageDescriptor" });
            }

            // MediumOfInstructionDescriptor (string) maxLength
            if (this.MediumOfInstructionDescriptor != null && this.MediumOfInstructionDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for MediumOfInstructionDescriptor, length must be less than 306.", new [] { "MediumOfInstructionDescriptor" });
            }

            // PopulationServedDescriptor (string) maxLength
            if (this.PopulationServedDescriptor != null && this.PopulationServedDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for PopulationServedDescriptor, length must be less than 306.", new [] { "PopulationServedDescriptor" });
            }

            // SectionName (string) maxLength
            if (this.SectionName != null && this.SectionName.Length > 100)
            {
                yield return new ValidationResult("Invalid value for SectionName, length must be less than 100.", new [] { "SectionName" });
            }

            yield break;
        }
    }

}
