// <auto-generated>
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.OdsApi.Sdk.v54.Client;

namespace EdFi.OdsApi.Sdk.v54.Models.All
{
    /// <summary>
    /// EdFiGradebookEntryReference
    /// </summary>
    public partial class EdFiGradebookEntryReference : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiGradebookEntryReference" /> class.
        /// </summary>
        /// <param name="dateAssigned">The date the assignment, homework, or assessment was assigned or executed.</param>
        /// <param name="gradebookEntryTitle">The name or title of the activity to be recorded in the GradebookEntry.</param>
        /// <param name="localCourseCode">The local code assigned by the School that identifies the course offering provided for the instruction of students.</param>
        /// <param name="schoolId">The identifier assigned to a school.</param>
        /// <param name="schoolYear">The identifier for the school year.</param>
        /// <param name="sectionIdentifier">The local identifier assigned to a section.</param>
        /// <param name="sessionName">The identifier for the calendar for the academic session (e.g., 2010/11, 2011 Summer).</param>
        /// <param name="link">link</param>
        [JsonConstructor]
        public EdFiGradebookEntryReference(DateOnly dateAssigned, string gradebookEntryTitle, string localCourseCode, int schoolId, int schoolYear, string sectionIdentifier, string sessionName, Option<Link?> link = default)
        {
            DateAssigned = dateAssigned;
            GradebookEntryTitle = gradebookEntryTitle;
            LocalCourseCode = localCourseCode;
            SchoolId = schoolId;
            SchoolYear = schoolYear;
            SectionIdentifier = sectionIdentifier;
            SessionName = sessionName;
            LinkOption = link;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The date the assignment, homework, or assessment was assigned or executed.
        /// </summary>
        /// <value>The date the assignment, homework, or assessment was assigned or executed.</value>
        [JsonPropertyName("dateAssigned")]
        public DateOnly DateAssigned { get; set; }

        /// <summary>
        /// The name or title of the activity to be recorded in the GradebookEntry.
        /// </summary>
        /// <value>The name or title of the activity to be recorded in the GradebookEntry.</value>
        [JsonPropertyName("gradebookEntryTitle")]
        public string GradebookEntryTitle { get; set; }

        /// <summary>
        /// The local code assigned by the School that identifies the course offering provided for the instruction of students.
        /// </summary>
        /// <value>The local code assigned by the School that identifies the course offering provided for the instruction of students.</value>
        [JsonPropertyName("localCourseCode")]
        public string LocalCourseCode { get; set; }

        /// <summary>
        /// The identifier assigned to a school.
        /// </summary>
        /// <value>The identifier assigned to a school.</value>
        [JsonPropertyName("schoolId")]
        public int SchoolId { get; set; }

        /// <summary>
        /// The identifier for the school year.
        /// </summary>
        /// <value>The identifier for the school year.</value>
        [JsonPropertyName("schoolYear")]
        public int SchoolYear { get; set; }

        /// <summary>
        /// The local identifier assigned to a section.
        /// </summary>
        /// <value>The local identifier assigned to a section.</value>
        [JsonPropertyName("sectionIdentifier")]
        public string SectionIdentifier { get; set; }

        /// <summary>
        /// The identifier for the calendar for the academic session (e.g., 2010/11, 2011 Summer).
        /// </summary>
        /// <value>The identifier for the calendar for the academic session (e.g., 2010/11, 2011 Summer).</value>
        [JsonPropertyName("sessionName")]
        public string SessionName { get; set; }

        /// <summary>
        /// Used to track the state of Link
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Link?> LinkOption { get; private set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        [JsonPropertyName("link")]
        public Link? Link { get { return this.LinkOption; } set { this.LinkOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiGradebookEntryReference {\n");
            sb.Append("  DateAssigned: ").Append(DateAssigned).Append("\n");
            sb.Append("  GradebookEntryTitle: ").Append(GradebookEntryTitle).Append("\n");
            sb.Append("  LocalCourseCode: ").Append(LocalCourseCode).Append("\n");
            sb.Append("  SchoolId: ").Append(SchoolId).Append("\n");
            sb.Append("  SchoolYear: ").Append(SchoolYear).Append("\n");
            sb.Append("  SectionIdentifier: ").Append(SectionIdentifier).Append("\n");
            sb.Append("  SessionName: ").Append(SessionName).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // GradebookEntryTitle (string) maxLength
            if (this.GradebookEntryTitle != null && this.GradebookEntryTitle.Length > 60)
            {
                yield return new ValidationResult("Invalid value for GradebookEntryTitle, length must be less than 60.", new [] { "GradebookEntryTitle" });
            }

            // LocalCourseCode (string) maxLength
            if (this.LocalCourseCode != null && this.LocalCourseCode.Length > 60)
            {
                yield return new ValidationResult("Invalid value for LocalCourseCode, length must be less than 60.", new [] { "LocalCourseCode" });
            }

            // SectionIdentifier (string) maxLength
            if (this.SectionIdentifier != null && this.SectionIdentifier.Length > 255)
            {
                yield return new ValidationResult("Invalid value for SectionIdentifier, length must be less than 255.", new [] { "SectionIdentifier" });
            }

            // SessionName (string) maxLength
            if (this.SessionName != null && this.SessionName.Length > 60)
            {
                yield return new ValidationResult("Invalid value for SessionName, length must be less than 60.", new [] { "SessionName" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdFiGradebookEntryReference" />
    /// </summary>
    public class EdFiGradebookEntryReferenceJsonConverter : JsonConverter<EdFiGradebookEntryReference>
    {
        /// <summary>
        /// The format to use to serialize DateAssigned
        /// </summary>
        public static string DateAssignedFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="EdFiGradebookEntryReference" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdFiGradebookEntryReference Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DateOnly?> dateAssigned = default;
            Option<string?> gradebookEntryTitle = default;
            Option<string?> localCourseCode = default;
            Option<int?> schoolId = default;
            Option<int?> schoolYear = default;
            Option<string?> sectionIdentifier = default;
            Option<string?> sessionName = default;
            Option<Link?> link = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "dateAssigned":
                            dateAssigned = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "gradebookEntryTitle":
                            gradebookEntryTitle = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "localCourseCode":
                            localCourseCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "schoolId":
                            schoolId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "schoolYear":
                            schoolYear = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "sectionIdentifier":
                            sectionIdentifier = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sessionName":
                            sessionName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "link":
                            link = new Option<Link?>(JsonSerializer.Deserialize<Link>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!dateAssigned.IsSet)
                throw new ArgumentException("Property is required for class EdFiGradebookEntryReference.", nameof(dateAssigned));

            if (!gradebookEntryTitle.IsSet)
                throw new ArgumentException("Property is required for class EdFiGradebookEntryReference.", nameof(gradebookEntryTitle));

            if (!localCourseCode.IsSet)
                throw new ArgumentException("Property is required for class EdFiGradebookEntryReference.", nameof(localCourseCode));

            if (!schoolId.IsSet)
                throw new ArgumentException("Property is required for class EdFiGradebookEntryReference.", nameof(schoolId));

            if (!schoolYear.IsSet)
                throw new ArgumentException("Property is required for class EdFiGradebookEntryReference.", nameof(schoolYear));

            if (!sectionIdentifier.IsSet)
                throw new ArgumentException("Property is required for class EdFiGradebookEntryReference.", nameof(sectionIdentifier));

            if (!sessionName.IsSet)
                throw new ArgumentException("Property is required for class EdFiGradebookEntryReference.", nameof(sessionName));

            if (dateAssigned.IsSet && dateAssigned.Value == null)
                throw new ArgumentNullException(nameof(dateAssigned), "Property is not nullable for class EdFiGradebookEntryReference.");

            if (gradebookEntryTitle.IsSet && gradebookEntryTitle.Value == null)
                throw new ArgumentNullException(nameof(gradebookEntryTitle), "Property is not nullable for class EdFiGradebookEntryReference.");

            if (localCourseCode.IsSet && localCourseCode.Value == null)
                throw new ArgumentNullException(nameof(localCourseCode), "Property is not nullable for class EdFiGradebookEntryReference.");

            if (schoolId.IsSet && schoolId.Value == null)
                throw new ArgumentNullException(nameof(schoolId), "Property is not nullable for class EdFiGradebookEntryReference.");

            if (schoolYear.IsSet && schoolYear.Value == null)
                throw new ArgumentNullException(nameof(schoolYear), "Property is not nullable for class EdFiGradebookEntryReference.");

            if (sectionIdentifier.IsSet && sectionIdentifier.Value == null)
                throw new ArgumentNullException(nameof(sectionIdentifier), "Property is not nullable for class EdFiGradebookEntryReference.");

            if (sessionName.IsSet && sessionName.Value == null)
                throw new ArgumentNullException(nameof(sessionName), "Property is not nullable for class EdFiGradebookEntryReference.");

            if (link.IsSet && link.Value == null)
                throw new ArgumentNullException(nameof(link), "Property is not nullable for class EdFiGradebookEntryReference.");

            return new EdFiGradebookEntryReference(dateAssigned.Value!.Value!, gradebookEntryTitle.Value!, localCourseCode.Value!, schoolId.Value!.Value!, schoolYear.Value!.Value!, sectionIdentifier.Value!, sessionName.Value!, link);
        }

        /// <summary>
        /// Serializes a <see cref="EdFiGradebookEntryReference" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiGradebookEntryReference"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdFiGradebookEntryReference edFiGradebookEntryReference, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edFiGradebookEntryReference, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdFiGradebookEntryReference" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiGradebookEntryReference"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdFiGradebookEntryReference edFiGradebookEntryReference, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edFiGradebookEntryReference.GradebookEntryTitle == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntryReference.GradebookEntryTitle), "Property is required for class EdFiGradebookEntryReference.");

            if (edFiGradebookEntryReference.LocalCourseCode == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntryReference.LocalCourseCode), "Property is required for class EdFiGradebookEntryReference.");

            if (edFiGradebookEntryReference.SectionIdentifier == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntryReference.SectionIdentifier), "Property is required for class EdFiGradebookEntryReference.");

            if (edFiGradebookEntryReference.SessionName == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntryReference.SessionName), "Property is required for class EdFiGradebookEntryReference.");

            if (edFiGradebookEntryReference.LinkOption.IsSet && edFiGradebookEntryReference.Link == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntryReference.Link), "Property is required for class EdFiGradebookEntryReference.");

            writer.WriteString("dateAssigned", edFiGradebookEntryReference.DateAssigned.ToString(DateAssignedFormat));

            writer.WriteString("gradebookEntryTitle", edFiGradebookEntryReference.GradebookEntryTitle);

            writer.WriteString("localCourseCode", edFiGradebookEntryReference.LocalCourseCode);

            writer.WriteNumber("schoolId", edFiGradebookEntryReference.SchoolId);

            writer.WriteNumber("schoolYear", edFiGradebookEntryReference.SchoolYear);

            writer.WriteString("sectionIdentifier", edFiGradebookEntryReference.SectionIdentifier);

            writer.WriteString("sessionName", edFiGradebookEntryReference.SessionName);

            if (edFiGradebookEntryReference.LinkOption.IsSet)
            {
                writer.WritePropertyName("link");
                JsonSerializer.Serialize(writer, edFiGradebookEntryReference.Link, jsonSerializerOptions);
            }
        }
    }
}
