// <auto-generated>
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.OdsApi.Sdk.v54.Client;

namespace EdFi.OdsApi.Sdk.v54.Models.All
{
    /// <summary>
    /// EdFiGradebookEntry
    /// </summary>
    public partial class EdFiGradebookEntry : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiGradebookEntry" /> class.
        /// </summary>
        /// <param name="dateAssigned">The date the assignment, homework, or assessment was assigned or executed.</param>
        /// <param name="gradebookEntryTitle">The name or title of the activity to be recorded in the GradebookEntry.</param>
        /// <param name="sectionReference">sectionReference</param>
        /// <param name="id">id</param>
        /// <param name="gradingPeriodReference">gradingPeriodReference</param>
        /// <param name="description">A description of the assignment, homework, or classroom assessment.</param>
        /// <param name="dueDate">The date the assignment, homework, or assessment is due.</param>
        /// <param name="gradebookEntryTypeDescriptor">The type of the GradebookEntry; for example, homework, assignment, quiz, unit test, oral presentation, etc.</param>
        /// <param name="learningObjectives">An unordered collection of gradebookEntryLearningObjectives. LearningObjectives associated with the GradebookEntry.</param>
        /// <param name="learningStandards">An unordered collection of gradebookEntryLearningStandards. LearningStandard(s) associated with the GradebookEntry.</param>
        /// <param name="etag">A unique system-generated value that identifies the version of the resource.</param>
        /// <param name="ext">Extensions to the GradebookEntry entity.</param>
        [JsonConstructor]
        public EdFiGradebookEntry(DateOnly dateAssigned, string gradebookEntryTitle, EdFiSectionReference sectionReference, Option<string?> id = default, Option<EdFiGradingPeriodReference?> gradingPeriodReference = default, Option<string?> description = default, Option<DateOnly?> dueDate = default, Option<string?> gradebookEntryTypeDescriptor = default, Option<List<EdFiGradebookEntryLearningObjective>?> learningObjectives = default, Option<List<EdFiGradebookEntryLearningStandard>?> learningStandards = default, Option<string?> etag = default, Option<Object?> ext = default)
        {
            DateAssigned = dateAssigned;
            GradebookEntryTitle = gradebookEntryTitle;
            SectionReference = sectionReference;
            IdOption = id;
            GradingPeriodReferenceOption = gradingPeriodReference;
            DescriptionOption = description;
            DueDateOption = dueDate;
            GradebookEntryTypeDescriptorOption = gradebookEntryTypeDescriptor;
            LearningObjectivesOption = learningObjectives;
            LearningStandardsOption = learningStandards;
            EtagOption = etag;
            ExtOption = ext;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The date the assignment, homework, or assessment was assigned or executed.
        /// </summary>
        /// <value>The date the assignment, homework, or assessment was assigned or executed.</value>
        [JsonPropertyName("dateAssigned")]
        public DateOnly DateAssigned { get; set; }

        /// <summary>
        /// The name or title of the activity to be recorded in the GradebookEntry.
        /// </summary>
        /// <value>The name or title of the activity to be recorded in the GradebookEntry.</value>
        [JsonPropertyName("gradebookEntryTitle")]
        public string GradebookEntryTitle { get; set; }

        /// <summary>
        /// Gets or Sets SectionReference
        /// </summary>
        [JsonPropertyName("sectionReference")]
        public EdFiSectionReference SectionReference { get; set; }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of GradingPeriodReference
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EdFiGradingPeriodReference?> GradingPeriodReferenceOption { get; private set; }

        /// <summary>
        /// Gets or Sets GradingPeriodReference
        /// </summary>
        [JsonPropertyName("gradingPeriodReference")]
        public EdFiGradingPeriodReference? GradingPeriodReference { get { return this.GradingPeriodReferenceOption; } set { this.GradingPeriodReferenceOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// A description of the assignment, homework, or classroom assessment.
        /// </summary>
        /// <value>A description of the assignment, homework, or classroom assessment.</value>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of DueDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> DueDateOption { get; private set; }

        /// <summary>
        /// The date the assignment, homework, or assessment is due.
        /// </summary>
        /// <value>The date the assignment, homework, or assessment is due.</value>
        [JsonPropertyName("dueDate")]
        public DateOnly? DueDate { get { return this.DueDateOption; } set { this.DueDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of GradebookEntryTypeDescriptor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GradebookEntryTypeDescriptorOption { get; private set; }

        /// <summary>
        /// The type of the GradebookEntry; for example, homework, assignment, quiz, unit test, oral presentation, etc.
        /// </summary>
        /// <value>The type of the GradebookEntry; for example, homework, assignment, quiz, unit test, oral presentation, etc.</value>
        [JsonPropertyName("gradebookEntryTypeDescriptor")]
        public string? GradebookEntryTypeDescriptor { get { return this.GradebookEntryTypeDescriptorOption; } set { this.GradebookEntryTypeDescriptorOption = new(value); } }

        /// <summary>
        /// Used to track the state of LearningObjectives
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<EdFiGradebookEntryLearningObjective>?> LearningObjectivesOption { get; private set; }

        /// <summary>
        /// An unordered collection of gradebookEntryLearningObjectives. LearningObjectives associated with the GradebookEntry.
        /// </summary>
        /// <value>An unordered collection of gradebookEntryLearningObjectives. LearningObjectives associated with the GradebookEntry.</value>
        [JsonPropertyName("learningObjectives")]
        public List<EdFiGradebookEntryLearningObjective>? LearningObjectives { get { return this.LearningObjectivesOption; } set { this.LearningObjectivesOption = new(value); } }

        /// <summary>
        /// Used to track the state of LearningStandards
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<EdFiGradebookEntryLearningStandard>?> LearningStandardsOption { get; private set; }

        /// <summary>
        /// An unordered collection of gradebookEntryLearningStandards. LearningStandard(s) associated with the GradebookEntry.
        /// </summary>
        /// <value>An unordered collection of gradebookEntryLearningStandards. LearningStandard(s) associated with the GradebookEntry.</value>
        [JsonPropertyName("learningStandards")]
        public List<EdFiGradebookEntryLearningStandard>? LearningStandards { get { return this.LearningStandardsOption; } set { this.LearningStandardsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Etag
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EtagOption { get; private set; }

        /// <summary>
        /// A unique system-generated value that identifies the version of the resource.
        /// </summary>
        /// <value>A unique system-generated value that identifies the version of the resource.</value>
        [JsonPropertyName("_etag")]
        public string? Etag { get { return this.EtagOption; } set { this.EtagOption = new(value); } }

        /// <summary>
        /// Used to track the state of Ext
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> ExtOption { get; private set; }

        /// <summary>
        /// Extensions to the GradebookEntry entity.
        /// </summary>
        /// <value>Extensions to the GradebookEntry entity.</value>
        [JsonPropertyName("_ext")]
        public Object? Ext { get { return this.ExtOption; } set { this.ExtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiGradebookEntry {\n");
            sb.Append("  DateAssigned: ").Append(DateAssigned).Append("\n");
            sb.Append("  GradebookEntryTitle: ").Append(GradebookEntryTitle).Append("\n");
            sb.Append("  SectionReference: ").Append(SectionReference).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  GradingPeriodReference: ").Append(GradingPeriodReference).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  DueDate: ").Append(DueDate).Append("\n");
            sb.Append("  GradebookEntryTypeDescriptor: ").Append(GradebookEntryTypeDescriptor).Append("\n");
            sb.Append("  LearningObjectives: ").Append(LearningObjectives).Append("\n");
            sb.Append("  LearningStandards: ").Append(LearningStandards).Append("\n");
            sb.Append("  Etag: ").Append(Etag).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // GradebookEntryTitle (string) maxLength
            if (this.GradebookEntryTitle != null && this.GradebookEntryTitle.Length > 60)
            {
                yield return new ValidationResult("Invalid value for GradebookEntryTitle, length must be less than 60.", new [] { "GradebookEntryTitle" });
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 1024)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 1024.", new [] { "Description" });
            }

            // GradebookEntryTypeDescriptor (string) maxLength
            if (this.GradebookEntryTypeDescriptor != null && this.GradebookEntryTypeDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for GradebookEntryTypeDescriptor, length must be less than 306.", new [] { "GradebookEntryTypeDescriptor" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdFiGradebookEntry" />
    /// </summary>
    public class EdFiGradebookEntryJsonConverter : JsonConverter<EdFiGradebookEntry>
    {
        /// <summary>
        /// The format to use to serialize DateAssigned
        /// </summary>
        public static string DateAssignedFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize DueDate
        /// </summary>
        public static string DueDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="EdFiGradebookEntry" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdFiGradebookEntry Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DateOnly?> dateAssigned = default;
            Option<string?> gradebookEntryTitle = default;
            Option<EdFiSectionReference?> sectionReference = default;
            Option<string?> id = default;
            Option<EdFiGradingPeriodReference?> gradingPeriodReference = default;
            Option<string?> description = default;
            Option<DateOnly?> dueDate = default;
            Option<string?> gradebookEntryTypeDescriptor = default;
            Option<List<EdFiGradebookEntryLearningObjective>?> learningObjectives = default;
            Option<List<EdFiGradebookEntryLearningStandard>?> learningStandards = default;
            Option<string?> etag = default;
            Option<Object?> ext = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "dateAssigned":
                            dateAssigned = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "gradebookEntryTitle":
                            gradebookEntryTitle = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sectionReference":
                            sectionReference = new Option<EdFiSectionReference?>(JsonSerializer.Deserialize<EdFiSectionReference>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "gradingPeriodReference":
                            gradingPeriodReference = new Option<EdFiGradingPeriodReference?>(JsonSerializer.Deserialize<EdFiGradingPeriodReference>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "dueDate":
                            dueDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "gradebookEntryTypeDescriptor":
                            gradebookEntryTypeDescriptor = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "learningObjectives":
                            learningObjectives = new Option<List<EdFiGradebookEntryLearningObjective>?>(JsonSerializer.Deserialize<List<EdFiGradebookEntryLearningObjective>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "learningStandards":
                            learningStandards = new Option<List<EdFiGradebookEntryLearningStandard>?>(JsonSerializer.Deserialize<List<EdFiGradebookEntryLearningStandard>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "_etag":
                            etag = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "_ext":
                            ext = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!dateAssigned.IsSet)
                throw new ArgumentException("Property is required for class EdFiGradebookEntry.", nameof(dateAssigned));

            if (!gradebookEntryTitle.IsSet)
                throw new ArgumentException("Property is required for class EdFiGradebookEntry.", nameof(gradebookEntryTitle));

            if (!sectionReference.IsSet)
                throw new ArgumentException("Property is required for class EdFiGradebookEntry.", nameof(sectionReference));

            if (dateAssigned.IsSet && dateAssigned.Value == null)
                throw new ArgumentNullException(nameof(dateAssigned), "Property is not nullable for class EdFiGradebookEntry.");

            if (gradebookEntryTitle.IsSet && gradebookEntryTitle.Value == null)
                throw new ArgumentNullException(nameof(gradebookEntryTitle), "Property is not nullable for class EdFiGradebookEntry.");

            if (sectionReference.IsSet && sectionReference.Value == null)
                throw new ArgumentNullException(nameof(sectionReference), "Property is not nullable for class EdFiGradebookEntry.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class EdFiGradebookEntry.");

            if (gradingPeriodReference.IsSet && gradingPeriodReference.Value == null)
                throw new ArgumentNullException(nameof(gradingPeriodReference), "Property is not nullable for class EdFiGradebookEntry.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class EdFiGradebookEntry.");

            if (dueDate.IsSet && dueDate.Value == null)
                throw new ArgumentNullException(nameof(dueDate), "Property is not nullable for class EdFiGradebookEntry.");

            if (gradebookEntryTypeDescriptor.IsSet && gradebookEntryTypeDescriptor.Value == null)
                throw new ArgumentNullException(nameof(gradebookEntryTypeDescriptor), "Property is not nullable for class EdFiGradebookEntry.");

            if (learningObjectives.IsSet && learningObjectives.Value == null)
                throw new ArgumentNullException(nameof(learningObjectives), "Property is not nullable for class EdFiGradebookEntry.");

            if (learningStandards.IsSet && learningStandards.Value == null)
                throw new ArgumentNullException(nameof(learningStandards), "Property is not nullable for class EdFiGradebookEntry.");

            if (etag.IsSet && etag.Value == null)
                throw new ArgumentNullException(nameof(etag), "Property is not nullable for class EdFiGradebookEntry.");

            if (ext.IsSet && ext.Value == null)
                throw new ArgumentNullException(nameof(ext), "Property is not nullable for class EdFiGradebookEntry.");

            return new EdFiGradebookEntry(dateAssigned.Value!.Value!, gradebookEntryTitle.Value!, sectionReference.Value!, id, gradingPeriodReference, description, dueDate, gradebookEntryTypeDescriptor, learningObjectives, learningStandards, etag, ext);
        }

        /// <summary>
        /// Serializes a <see cref="EdFiGradebookEntry" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiGradebookEntry"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdFiGradebookEntry edFiGradebookEntry, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edFiGradebookEntry, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdFiGradebookEntry" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiGradebookEntry"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdFiGradebookEntry edFiGradebookEntry, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edFiGradebookEntry.GradebookEntryTitle == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntry.GradebookEntryTitle), "Property is required for class EdFiGradebookEntry.");

            if (edFiGradebookEntry.SectionReference == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntry.SectionReference), "Property is required for class EdFiGradebookEntry.");

            if (edFiGradebookEntry.IdOption.IsSet && edFiGradebookEntry.Id == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntry.Id), "Property is required for class EdFiGradebookEntry.");

            if (edFiGradebookEntry.GradingPeriodReferenceOption.IsSet && edFiGradebookEntry.GradingPeriodReference == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntry.GradingPeriodReference), "Property is required for class EdFiGradebookEntry.");

            if (edFiGradebookEntry.DescriptionOption.IsSet && edFiGradebookEntry.Description == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntry.Description), "Property is required for class EdFiGradebookEntry.");

            if (edFiGradebookEntry.GradebookEntryTypeDescriptorOption.IsSet && edFiGradebookEntry.GradebookEntryTypeDescriptor == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntry.GradebookEntryTypeDescriptor), "Property is required for class EdFiGradebookEntry.");

            if (edFiGradebookEntry.LearningObjectivesOption.IsSet && edFiGradebookEntry.LearningObjectives == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntry.LearningObjectives), "Property is required for class EdFiGradebookEntry.");

            if (edFiGradebookEntry.LearningStandardsOption.IsSet && edFiGradebookEntry.LearningStandards == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntry.LearningStandards), "Property is required for class EdFiGradebookEntry.");

            if (edFiGradebookEntry.EtagOption.IsSet && edFiGradebookEntry.Etag == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntry.Etag), "Property is required for class EdFiGradebookEntry.");

            if (edFiGradebookEntry.ExtOption.IsSet && edFiGradebookEntry.Ext == null)
                throw new ArgumentNullException(nameof(edFiGradebookEntry.Ext), "Property is required for class EdFiGradebookEntry.");

            writer.WriteString("dateAssigned", edFiGradebookEntry.DateAssigned.ToString(DateAssignedFormat));

            writer.WriteString("gradebookEntryTitle", edFiGradebookEntry.GradebookEntryTitle);

            writer.WritePropertyName("sectionReference");
            JsonSerializer.Serialize(writer, edFiGradebookEntry.SectionReference, jsonSerializerOptions);
            if (edFiGradebookEntry.IdOption.IsSet)
                writer.WriteString("id", edFiGradebookEntry.Id);

            if (edFiGradebookEntry.GradingPeriodReferenceOption.IsSet)
            {
                writer.WritePropertyName("gradingPeriodReference");
                JsonSerializer.Serialize(writer, edFiGradebookEntry.GradingPeriodReference, jsonSerializerOptions);
            }
            if (edFiGradebookEntry.DescriptionOption.IsSet)
                writer.WriteString("description", edFiGradebookEntry.Description);

            if (edFiGradebookEntry.DueDateOption.IsSet)
                writer.WriteString("dueDate", edFiGradebookEntry.DueDateOption.Value!.Value.ToString(DueDateFormat));

            if (edFiGradebookEntry.GradebookEntryTypeDescriptorOption.IsSet)
                writer.WriteString("gradebookEntryTypeDescriptor", edFiGradebookEntry.GradebookEntryTypeDescriptor);

            if (edFiGradebookEntry.LearningObjectivesOption.IsSet)
            {
                writer.WritePropertyName("learningObjectives");
                JsonSerializer.Serialize(writer, edFiGradebookEntry.LearningObjectives, jsonSerializerOptions);
            }
            if (edFiGradebookEntry.LearningStandardsOption.IsSet)
            {
                writer.WritePropertyName("learningStandards");
                JsonSerializer.Serialize(writer, edFiGradebookEntry.LearningStandards, jsonSerializerOptions);
            }
            if (edFiGradebookEntry.EtagOption.IsSet)
                writer.WriteString("_etag", edFiGradebookEntry.Etag);

            if (edFiGradebookEntry.ExtOption.IsSet)
            {
                writer.WritePropertyName("_ext");
                JsonSerializer.Serialize(writer, edFiGradebookEntry.Ext, jsonSerializerOptions);
            }
        }
    }
}
