// <auto-generated>
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.OdsApi.Sdk.v54.Client;

namespace EdFi.OdsApi.Sdk.v54.Models.All
{
    /// <summary>
    /// EdFiStudentAcademicRecordAcademicHonor
    /// </summary>
    public partial class EdFiStudentAcademicRecordAcademicHonor : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiStudentAcademicRecordAcademicHonor" /> class.
        /// </summary>
        /// <param name="academicHonorCategoryDescriptor">A designation of the type of academic distinctions earned by or awarded to the student.</param>
        /// <param name="honorDescription">A description of the type of academic distinctions earned by or awarded to the individual.</param>
        /// <param name="achievementCategoryDescriptor">The category of achievement attributed to the learner.</param>
        /// <param name="achievementCategorySystem">The system that defines the categories by which an achievement is attributed to the learner.</param>
        /// <param name="achievementTitle">The title assigned to the achievement.</param>
        /// <param name="criteria">The criteria for competency-based completion of the achievement/award.</param>
        /// <param name="criteriaURL">The Uniform Resource Locator (URL) for the unique address of a web page describing the competency-based completion criteria for the achievement/award.</param>
        /// <param name="evidenceStatement">A statement or reference describing the evidence that the learner met the criteria for attainment of the Achievement.</param>
        /// <param name="honorAwardDate">The date the honor was awarded or earned.</param>
        /// <param name="honorAwardExpiresDate">Date on which the award expires.</param>
        /// <param name="imageURL">The Uniform Resource Locator (URL) for the unique address of an image representing an award or badge associated with the Achievement.</param>
        /// <param name="issuerName">The name of the agent, entity, or institution issuing the element.</param>
        /// <param name="issuerOriginURL">The Uniform Resource Locator (URL) from which the award was issued.</param>
        /// <param name="ext">Extensions to the StudentAcademicRecordAcademicHonor entity.</param>
        [JsonConstructor]
        public EdFiStudentAcademicRecordAcademicHonor(string academicHonorCategoryDescriptor, string honorDescription, Option<string?> achievementCategoryDescriptor = default, Option<string?> achievementCategorySystem = default, Option<string?> achievementTitle = default, Option<string?> criteria = default, Option<string?> criteriaURL = default, Option<string?> evidenceStatement = default, Option<DateOnly?> honorAwardDate = default, Option<DateOnly?> honorAwardExpiresDate = default, Option<string?> imageURL = default, Option<string?> issuerName = default, Option<string?> issuerOriginURL = default, Option<Object?> ext = default)
        {
            AcademicHonorCategoryDescriptor = academicHonorCategoryDescriptor;
            HonorDescription = honorDescription;
            AchievementCategoryDescriptorOption = achievementCategoryDescriptor;
            AchievementCategorySystemOption = achievementCategorySystem;
            AchievementTitleOption = achievementTitle;
            CriteriaOption = criteria;
            CriteriaURLOption = criteriaURL;
            EvidenceStatementOption = evidenceStatement;
            HonorAwardDateOption = honorAwardDate;
            HonorAwardExpiresDateOption = honorAwardExpiresDate;
            ImageURLOption = imageURL;
            IssuerNameOption = issuerName;
            IssuerOriginURLOption = issuerOriginURL;
            ExtOption = ext;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// A designation of the type of academic distinctions earned by or awarded to the student.
        /// </summary>
        /// <value>A designation of the type of academic distinctions earned by or awarded to the student.</value>
        [JsonPropertyName("academicHonorCategoryDescriptor")]
        public string AcademicHonorCategoryDescriptor { get; set; }

        /// <summary>
        /// A description of the type of academic distinctions earned by or awarded to the individual.
        /// </summary>
        /// <value>A description of the type of academic distinctions earned by or awarded to the individual.</value>
        [JsonPropertyName("honorDescription")]
        public string HonorDescription { get; set; }

        /// <summary>
        /// Used to track the state of AchievementCategoryDescriptor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AchievementCategoryDescriptorOption { get; private set; }

        /// <summary>
        /// The category of achievement attributed to the learner.
        /// </summary>
        /// <value>The category of achievement attributed to the learner.</value>
        [JsonPropertyName("achievementCategoryDescriptor")]
        public string? AchievementCategoryDescriptor { get { return this.AchievementCategoryDescriptorOption; } set { this.AchievementCategoryDescriptorOption = new(value); } }

        /// <summary>
        /// Used to track the state of AchievementCategorySystem
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AchievementCategorySystemOption { get; private set; }

        /// <summary>
        /// The system that defines the categories by which an achievement is attributed to the learner.
        /// </summary>
        /// <value>The system that defines the categories by which an achievement is attributed to the learner.</value>
        [JsonPropertyName("achievementCategorySystem")]
        public string? AchievementCategorySystem { get { return this.AchievementCategorySystemOption; } set { this.AchievementCategorySystemOption = new(value); } }

        /// <summary>
        /// Used to track the state of AchievementTitle
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AchievementTitleOption { get; private set; }

        /// <summary>
        /// The title assigned to the achievement.
        /// </summary>
        /// <value>The title assigned to the achievement.</value>
        [JsonPropertyName("achievementTitle")]
        public string? AchievementTitle { get { return this.AchievementTitleOption; } set { this.AchievementTitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Criteria
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CriteriaOption { get; private set; }

        /// <summary>
        /// The criteria for competency-based completion of the achievement/award.
        /// </summary>
        /// <value>The criteria for competency-based completion of the achievement/award.</value>
        [JsonPropertyName("criteria")]
        public string? Criteria { get { return this.CriteriaOption; } set { this.CriteriaOption = new(value); } }

        /// <summary>
        /// Used to track the state of CriteriaURL
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CriteriaURLOption { get; private set; }

        /// <summary>
        /// The Uniform Resource Locator (URL) for the unique address of a web page describing the competency-based completion criteria for the achievement/award.
        /// </summary>
        /// <value>The Uniform Resource Locator (URL) for the unique address of a web page describing the competency-based completion criteria for the achievement/award.</value>
        [JsonPropertyName("criteriaURL")]
        public string? CriteriaURL { get { return this.CriteriaURLOption; } set { this.CriteriaURLOption = new(value); } }

        /// <summary>
        /// Used to track the state of EvidenceStatement
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EvidenceStatementOption { get; private set; }

        /// <summary>
        /// A statement or reference describing the evidence that the learner met the criteria for attainment of the Achievement.
        /// </summary>
        /// <value>A statement or reference describing the evidence that the learner met the criteria for attainment of the Achievement.</value>
        [JsonPropertyName("evidenceStatement")]
        public string? EvidenceStatement { get { return this.EvidenceStatementOption; } set { this.EvidenceStatementOption = new(value); } }

        /// <summary>
        /// Used to track the state of HonorAwardDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> HonorAwardDateOption { get; private set; }

        /// <summary>
        /// The date the honor was awarded or earned.
        /// </summary>
        /// <value>The date the honor was awarded or earned.</value>
        [JsonPropertyName("honorAwardDate")]
        public DateOnly? HonorAwardDate { get { return this.HonorAwardDateOption; } set { this.HonorAwardDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of HonorAwardExpiresDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> HonorAwardExpiresDateOption { get; private set; }

        /// <summary>
        /// Date on which the award expires.
        /// </summary>
        /// <value>Date on which the award expires.</value>
        [JsonPropertyName("honorAwardExpiresDate")]
        public DateOnly? HonorAwardExpiresDate { get { return this.HonorAwardExpiresDateOption; } set { this.HonorAwardExpiresDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of ImageURL
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ImageURLOption { get; private set; }

        /// <summary>
        /// The Uniform Resource Locator (URL) for the unique address of an image representing an award or badge associated with the Achievement.
        /// </summary>
        /// <value>The Uniform Resource Locator (URL) for the unique address of an image representing an award or badge associated with the Achievement.</value>
        [JsonPropertyName("imageURL")]
        public string? ImageURL { get { return this.ImageURLOption; } set { this.ImageURLOption = new(value); } }

        /// <summary>
        /// Used to track the state of IssuerName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IssuerNameOption { get; private set; }

        /// <summary>
        /// The name of the agent, entity, or institution issuing the element.
        /// </summary>
        /// <value>The name of the agent, entity, or institution issuing the element.</value>
        [JsonPropertyName("issuerName")]
        public string? IssuerName { get { return this.IssuerNameOption; } set { this.IssuerNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of IssuerOriginURL
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IssuerOriginURLOption { get; private set; }

        /// <summary>
        /// The Uniform Resource Locator (URL) from which the award was issued.
        /// </summary>
        /// <value>The Uniform Resource Locator (URL) from which the award was issued.</value>
        [JsonPropertyName("issuerOriginURL")]
        public string? IssuerOriginURL { get { return this.IssuerOriginURLOption; } set { this.IssuerOriginURLOption = new(value); } }

        /// <summary>
        /// Used to track the state of Ext
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> ExtOption { get; private set; }

        /// <summary>
        /// Extensions to the StudentAcademicRecordAcademicHonor entity.
        /// </summary>
        /// <value>Extensions to the StudentAcademicRecordAcademicHonor entity.</value>
        [JsonPropertyName("_ext")]
        public Object? Ext { get { return this.ExtOption; } set { this.ExtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiStudentAcademicRecordAcademicHonor {\n");
            sb.Append("  AcademicHonorCategoryDescriptor: ").Append(AcademicHonorCategoryDescriptor).Append("\n");
            sb.Append("  HonorDescription: ").Append(HonorDescription).Append("\n");
            sb.Append("  AchievementCategoryDescriptor: ").Append(AchievementCategoryDescriptor).Append("\n");
            sb.Append("  AchievementCategorySystem: ").Append(AchievementCategorySystem).Append("\n");
            sb.Append("  AchievementTitle: ").Append(AchievementTitle).Append("\n");
            sb.Append("  Criteria: ").Append(Criteria).Append("\n");
            sb.Append("  CriteriaURL: ").Append(CriteriaURL).Append("\n");
            sb.Append("  EvidenceStatement: ").Append(EvidenceStatement).Append("\n");
            sb.Append("  HonorAwardDate: ").Append(HonorAwardDate).Append("\n");
            sb.Append("  HonorAwardExpiresDate: ").Append(HonorAwardExpiresDate).Append("\n");
            sb.Append("  ImageURL: ").Append(ImageURL).Append("\n");
            sb.Append("  IssuerName: ").Append(IssuerName).Append("\n");
            sb.Append("  IssuerOriginURL: ").Append(IssuerOriginURL).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // AcademicHonorCategoryDescriptor (string) maxLength
            if (this.AcademicHonorCategoryDescriptor != null && this.AcademicHonorCategoryDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for AcademicHonorCategoryDescriptor, length must be less than 306.", new [] { "AcademicHonorCategoryDescriptor" });
            }

            // HonorDescription (string) maxLength
            if (this.HonorDescription != null && this.HonorDescription.Length > 80)
            {
                yield return new ValidationResult("Invalid value for HonorDescription, length must be less than 80.", new [] { "HonorDescription" });
            }

            // AchievementCategoryDescriptor (string) maxLength
            if (this.AchievementCategoryDescriptor != null && this.AchievementCategoryDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for AchievementCategoryDescriptor, length must be less than 306.", new [] { "AchievementCategoryDescriptor" });
            }

            // AchievementCategorySystem (string) maxLength
            if (this.AchievementCategorySystem != null && this.AchievementCategorySystem.Length > 60)
            {
                yield return new ValidationResult("Invalid value for AchievementCategorySystem, length must be less than 60.", new [] { "AchievementCategorySystem" });
            }

            // AchievementTitle (string) maxLength
            if (this.AchievementTitle != null && this.AchievementTitle.Length > 60)
            {
                yield return new ValidationResult("Invalid value for AchievementTitle, length must be less than 60.", new [] { "AchievementTitle" });
            }

            // Criteria (string) maxLength
            if (this.Criteria != null && this.Criteria.Length > 150)
            {
                yield return new ValidationResult("Invalid value for Criteria, length must be less than 150.", new [] { "Criteria" });
            }

            // CriteriaURL (string) maxLength
            if (this.CriteriaURL != null && this.CriteriaURL.Length > 255)
            {
                yield return new ValidationResult("Invalid value for CriteriaURL, length must be less than 255.", new [] { "CriteriaURL" });
            }

            // EvidenceStatement (string) maxLength
            if (this.EvidenceStatement != null && this.EvidenceStatement.Length > 150)
            {
                yield return new ValidationResult("Invalid value for EvidenceStatement, length must be less than 150.", new [] { "EvidenceStatement" });
            }

            // ImageURL (string) maxLength
            if (this.ImageURL != null && this.ImageURL.Length > 255)
            {
                yield return new ValidationResult("Invalid value for ImageURL, length must be less than 255.", new [] { "ImageURL" });
            }

            // IssuerName (string) maxLength
            if (this.IssuerName != null && this.IssuerName.Length > 150)
            {
                yield return new ValidationResult("Invalid value for IssuerName, length must be less than 150.", new [] { "IssuerName" });
            }

            // IssuerOriginURL (string) maxLength
            if (this.IssuerOriginURL != null && this.IssuerOriginURL.Length > 255)
            {
                yield return new ValidationResult("Invalid value for IssuerOriginURL, length must be less than 255.", new [] { "IssuerOriginURL" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdFiStudentAcademicRecordAcademicHonor" />
    /// </summary>
    public class EdFiStudentAcademicRecordAcademicHonorJsonConverter : JsonConverter<EdFiStudentAcademicRecordAcademicHonor>
    {
        /// <summary>
        /// The format to use to serialize HonorAwardDate
        /// </summary>
        public static string HonorAwardDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize HonorAwardExpiresDate
        /// </summary>
        public static string HonorAwardExpiresDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="EdFiStudentAcademicRecordAcademicHonor" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdFiStudentAcademicRecordAcademicHonor Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> academicHonorCategoryDescriptor = default;
            Option<string?> honorDescription = default;
            Option<string?> achievementCategoryDescriptor = default;
            Option<string?> achievementCategorySystem = default;
            Option<string?> achievementTitle = default;
            Option<string?> criteria = default;
            Option<string?> criteriaURL = default;
            Option<string?> evidenceStatement = default;
            Option<DateOnly?> honorAwardDate = default;
            Option<DateOnly?> honorAwardExpiresDate = default;
            Option<string?> imageURL = default;
            Option<string?> issuerName = default;
            Option<string?> issuerOriginURL = default;
            Option<Object?> ext = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "academicHonorCategoryDescriptor":
                            academicHonorCategoryDescriptor = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "honorDescription":
                            honorDescription = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "achievementCategoryDescriptor":
                            achievementCategoryDescriptor = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "achievementCategorySystem":
                            achievementCategorySystem = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "achievementTitle":
                            achievementTitle = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "criteria":
                            criteria = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "criteriaURL":
                            criteriaURL = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "evidenceStatement":
                            evidenceStatement = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "honorAwardDate":
                            honorAwardDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "honorAwardExpiresDate":
                            honorAwardExpiresDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "imageURL":
                            imageURL = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "issuerName":
                            issuerName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "issuerOriginURL":
                            issuerOriginURL = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "_ext":
                            ext = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!academicHonorCategoryDescriptor.IsSet)
                throw new ArgumentException("Property is required for class EdFiStudentAcademicRecordAcademicHonor.", nameof(academicHonorCategoryDescriptor));

            if (!honorDescription.IsSet)
                throw new ArgumentException("Property is required for class EdFiStudentAcademicRecordAcademicHonor.", nameof(honorDescription));

            if (academicHonorCategoryDescriptor.IsSet && academicHonorCategoryDescriptor.Value == null)
                throw new ArgumentNullException(nameof(academicHonorCategoryDescriptor), "Property is not nullable for class EdFiStudentAcademicRecordAcademicHonor.");

            if (honorDescription.IsSet && honorDescription.Value == null)
                throw new ArgumentNullException(nameof(honorDescription), "Property is not nullable for class EdFiStudentAcademicRecordAcademicHonor.");

            if (achievementCategoryDescriptor.IsSet && achievementCategoryDescriptor.Value == null)
                throw new ArgumentNullException(nameof(achievementCategoryDescriptor), "Property is not nullable for class EdFiStudentAcademicRecordAcademicHonor.");

            if (achievementCategorySystem.IsSet && achievementCategorySystem.Value == null)
                throw new ArgumentNullException(nameof(achievementCategorySystem), "Property is not nullable for class EdFiStudentAcademicRecordAcademicHonor.");

            if (achievementTitle.IsSet && achievementTitle.Value == null)
                throw new ArgumentNullException(nameof(achievementTitle), "Property is not nullable for class EdFiStudentAcademicRecordAcademicHonor.");

            if (criteria.IsSet && criteria.Value == null)
                throw new ArgumentNullException(nameof(criteria), "Property is not nullable for class EdFiStudentAcademicRecordAcademicHonor.");

            if (criteriaURL.IsSet && criteriaURL.Value == null)
                throw new ArgumentNullException(nameof(criteriaURL), "Property is not nullable for class EdFiStudentAcademicRecordAcademicHonor.");

            if (evidenceStatement.IsSet && evidenceStatement.Value == null)
                throw new ArgumentNullException(nameof(evidenceStatement), "Property is not nullable for class EdFiStudentAcademicRecordAcademicHonor.");

            if (honorAwardDate.IsSet && honorAwardDate.Value == null)
                throw new ArgumentNullException(nameof(honorAwardDate), "Property is not nullable for class EdFiStudentAcademicRecordAcademicHonor.");

            if (honorAwardExpiresDate.IsSet && honorAwardExpiresDate.Value == null)
                throw new ArgumentNullException(nameof(honorAwardExpiresDate), "Property is not nullable for class EdFiStudentAcademicRecordAcademicHonor.");

            if (imageURL.IsSet && imageURL.Value == null)
                throw new ArgumentNullException(nameof(imageURL), "Property is not nullable for class EdFiStudentAcademicRecordAcademicHonor.");

            if (issuerName.IsSet && issuerName.Value == null)
                throw new ArgumentNullException(nameof(issuerName), "Property is not nullable for class EdFiStudentAcademicRecordAcademicHonor.");

            if (issuerOriginURL.IsSet && issuerOriginURL.Value == null)
                throw new ArgumentNullException(nameof(issuerOriginURL), "Property is not nullable for class EdFiStudentAcademicRecordAcademicHonor.");

            if (ext.IsSet && ext.Value == null)
                throw new ArgumentNullException(nameof(ext), "Property is not nullable for class EdFiStudentAcademicRecordAcademicHonor.");

            return new EdFiStudentAcademicRecordAcademicHonor(academicHonorCategoryDescriptor.Value!, honorDescription.Value!, achievementCategoryDescriptor, achievementCategorySystem, achievementTitle, criteria, criteriaURL, evidenceStatement, honorAwardDate, honorAwardExpiresDate, imageURL, issuerName, issuerOriginURL, ext);
        }

        /// <summary>
        /// Serializes a <see cref="EdFiStudentAcademicRecordAcademicHonor" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiStudentAcademicRecordAcademicHonor"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdFiStudentAcademicRecordAcademicHonor edFiStudentAcademicRecordAcademicHonor, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edFiStudentAcademicRecordAcademicHonor, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdFiStudentAcademicRecordAcademicHonor" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiStudentAcademicRecordAcademicHonor"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdFiStudentAcademicRecordAcademicHonor edFiStudentAcademicRecordAcademicHonor, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edFiStudentAcademicRecordAcademicHonor.AcademicHonorCategoryDescriptor == null)
                throw new ArgumentNullException(nameof(edFiStudentAcademicRecordAcademicHonor.AcademicHonorCategoryDescriptor), "Property is required for class EdFiStudentAcademicRecordAcademicHonor.");

            if (edFiStudentAcademicRecordAcademicHonor.HonorDescription == null)
                throw new ArgumentNullException(nameof(edFiStudentAcademicRecordAcademicHonor.HonorDescription), "Property is required for class EdFiStudentAcademicRecordAcademicHonor.");

            if (edFiStudentAcademicRecordAcademicHonor.AchievementCategoryDescriptorOption.IsSet && edFiStudentAcademicRecordAcademicHonor.AchievementCategoryDescriptor == null)
                throw new ArgumentNullException(nameof(edFiStudentAcademicRecordAcademicHonor.AchievementCategoryDescriptor), "Property is required for class EdFiStudentAcademicRecordAcademicHonor.");

            if (edFiStudentAcademicRecordAcademicHonor.AchievementCategorySystemOption.IsSet && edFiStudentAcademicRecordAcademicHonor.AchievementCategorySystem == null)
                throw new ArgumentNullException(nameof(edFiStudentAcademicRecordAcademicHonor.AchievementCategorySystem), "Property is required for class EdFiStudentAcademicRecordAcademicHonor.");

            if (edFiStudentAcademicRecordAcademicHonor.AchievementTitleOption.IsSet && edFiStudentAcademicRecordAcademicHonor.AchievementTitle == null)
                throw new ArgumentNullException(nameof(edFiStudentAcademicRecordAcademicHonor.AchievementTitle), "Property is required for class EdFiStudentAcademicRecordAcademicHonor.");

            if (edFiStudentAcademicRecordAcademicHonor.CriteriaOption.IsSet && edFiStudentAcademicRecordAcademicHonor.Criteria == null)
                throw new ArgumentNullException(nameof(edFiStudentAcademicRecordAcademicHonor.Criteria), "Property is required for class EdFiStudentAcademicRecordAcademicHonor.");

            if (edFiStudentAcademicRecordAcademicHonor.CriteriaURLOption.IsSet && edFiStudentAcademicRecordAcademicHonor.CriteriaURL == null)
                throw new ArgumentNullException(nameof(edFiStudentAcademicRecordAcademicHonor.CriteriaURL), "Property is required for class EdFiStudentAcademicRecordAcademicHonor.");

            if (edFiStudentAcademicRecordAcademicHonor.EvidenceStatementOption.IsSet && edFiStudentAcademicRecordAcademicHonor.EvidenceStatement == null)
                throw new ArgumentNullException(nameof(edFiStudentAcademicRecordAcademicHonor.EvidenceStatement), "Property is required for class EdFiStudentAcademicRecordAcademicHonor.");

            if (edFiStudentAcademicRecordAcademicHonor.ImageURLOption.IsSet && edFiStudentAcademicRecordAcademicHonor.ImageURL == null)
                throw new ArgumentNullException(nameof(edFiStudentAcademicRecordAcademicHonor.ImageURL), "Property is required for class EdFiStudentAcademicRecordAcademicHonor.");

            if (edFiStudentAcademicRecordAcademicHonor.IssuerNameOption.IsSet && edFiStudentAcademicRecordAcademicHonor.IssuerName == null)
                throw new ArgumentNullException(nameof(edFiStudentAcademicRecordAcademicHonor.IssuerName), "Property is required for class EdFiStudentAcademicRecordAcademicHonor.");

            if (edFiStudentAcademicRecordAcademicHonor.IssuerOriginURLOption.IsSet && edFiStudentAcademicRecordAcademicHonor.IssuerOriginURL == null)
                throw new ArgumentNullException(nameof(edFiStudentAcademicRecordAcademicHonor.IssuerOriginURL), "Property is required for class EdFiStudentAcademicRecordAcademicHonor.");

            if (edFiStudentAcademicRecordAcademicHonor.ExtOption.IsSet && edFiStudentAcademicRecordAcademicHonor.Ext == null)
                throw new ArgumentNullException(nameof(edFiStudentAcademicRecordAcademicHonor.Ext), "Property is required for class EdFiStudentAcademicRecordAcademicHonor.");

            writer.WriteString("academicHonorCategoryDescriptor", edFiStudentAcademicRecordAcademicHonor.AcademicHonorCategoryDescriptor);

            writer.WriteString("honorDescription", edFiStudentAcademicRecordAcademicHonor.HonorDescription);

            if (edFiStudentAcademicRecordAcademicHonor.AchievementCategoryDescriptorOption.IsSet)
                writer.WriteString("achievementCategoryDescriptor", edFiStudentAcademicRecordAcademicHonor.AchievementCategoryDescriptor);

            if (edFiStudentAcademicRecordAcademicHonor.AchievementCategorySystemOption.IsSet)
                writer.WriteString("achievementCategorySystem", edFiStudentAcademicRecordAcademicHonor.AchievementCategorySystem);

            if (edFiStudentAcademicRecordAcademicHonor.AchievementTitleOption.IsSet)
                writer.WriteString("achievementTitle", edFiStudentAcademicRecordAcademicHonor.AchievementTitle);

            if (edFiStudentAcademicRecordAcademicHonor.CriteriaOption.IsSet)
                writer.WriteString("criteria", edFiStudentAcademicRecordAcademicHonor.Criteria);

            if (edFiStudentAcademicRecordAcademicHonor.CriteriaURLOption.IsSet)
                writer.WriteString("criteriaURL", edFiStudentAcademicRecordAcademicHonor.CriteriaURL);

            if (edFiStudentAcademicRecordAcademicHonor.EvidenceStatementOption.IsSet)
                writer.WriteString("evidenceStatement", edFiStudentAcademicRecordAcademicHonor.EvidenceStatement);

            if (edFiStudentAcademicRecordAcademicHonor.HonorAwardDateOption.IsSet)
                writer.WriteString("honorAwardDate", edFiStudentAcademicRecordAcademicHonor.HonorAwardDateOption.Value!.Value.ToString(HonorAwardDateFormat));

            if (edFiStudentAcademicRecordAcademicHonor.HonorAwardExpiresDateOption.IsSet)
                writer.WriteString("honorAwardExpiresDate", edFiStudentAcademicRecordAcademicHonor.HonorAwardExpiresDateOption.Value!.Value.ToString(HonorAwardExpiresDateFormat));

            if (edFiStudentAcademicRecordAcademicHonor.ImageURLOption.IsSet)
                writer.WriteString("imageURL", edFiStudentAcademicRecordAcademicHonor.ImageURL);

            if (edFiStudentAcademicRecordAcademicHonor.IssuerNameOption.IsSet)
                writer.WriteString("issuerName", edFiStudentAcademicRecordAcademicHonor.IssuerName);

            if (edFiStudentAcademicRecordAcademicHonor.IssuerOriginURLOption.IsSet)
                writer.WriteString("issuerOriginURL", edFiStudentAcademicRecordAcademicHonor.IssuerOriginURL);

            if (edFiStudentAcademicRecordAcademicHonor.ExtOption.IsSet)
            {
                writer.WritePropertyName("_ext");
                JsonSerializer.Serialize(writer, edFiStudentAcademicRecordAcademicHonor.Ext, jsonSerializerOptions);
            }
        }
    }
}
