// <auto-generated>
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EdFi.OdsApi.Sdk.v54.Client;

namespace EdFi.OdsApi.Sdk.v54.Models.All
{
    /// <summary>
    /// EdFiStudentSectionAssociation
    /// </summary>
    public partial class EdFiStudentSectionAssociation : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiStudentSectionAssociation" /> class.
        /// </summary>
        /// <param name="beginDate">Month, day, and year of the Student&#39;s entry or assignment to the Section.</param>
        /// <param name="sectionReference">sectionReference</param>
        /// <param name="studentReference">studentReference</param>
        /// <param name="id">id</param>
        /// <param name="attemptStatusDescriptor">An indication of the student&#39;s completion status for the section.</param>
        /// <param name="endDate">Month, day, and year of the withdrawal or exit of the Student from the Section.</param>
        /// <param name="homeroomIndicator">Indicates the Section is the student&#39;s homeroom. Homeroom period may the convention for taking daily attendance.</param>
        /// <param name="repeatIdentifierDescriptor">An indication as to whether a student has previously taken a given course.        Repeated, counted in grade point average        Repeated, not counted in grade point average        Not repeated        Other.</param>
        /// <param name="teacherStudentDataLinkExclusion">Indicates that the student-section combination is excluded from calculation of value-added or growth attribution calculations used for a particular teacher evaluation.</param>
        /// <param name="etag">A unique system-generated value that identifies the version of the resource.</param>
        /// <param name="ext">Extensions to the StudentSectionAssociation entity.</param>
        [JsonConstructor]
        public EdFiStudentSectionAssociation(DateOnly beginDate, EdFiSectionReference sectionReference, EdFiStudentReference studentReference, Option<string?> id = default, Option<string?> attemptStatusDescriptor = default, Option<DateOnly?> endDate = default, Option<bool?> homeroomIndicator = default, Option<string?> repeatIdentifierDescriptor = default, Option<bool?> teacherStudentDataLinkExclusion = default, Option<string?> etag = default, Option<Object?> ext = default)
        {
            BeginDate = beginDate;
            SectionReference = sectionReference;
            StudentReference = studentReference;
            IdOption = id;
            AttemptStatusDescriptorOption = attemptStatusDescriptor;
            EndDateOption = endDate;
            HomeroomIndicatorOption = homeroomIndicator;
            RepeatIdentifierDescriptorOption = repeatIdentifierDescriptor;
            TeacherStudentDataLinkExclusionOption = teacherStudentDataLinkExclusion;
            EtagOption = etag;
            ExtOption = ext;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Month, day, and year of the Student&#39;s entry or assignment to the Section.
        /// </summary>
        /// <value>Month, day, and year of the Student&#39;s entry or assignment to the Section.</value>
        [JsonPropertyName("beginDate")]
        public DateOnly BeginDate { get; set; }

        /// <summary>
        /// Gets or Sets SectionReference
        /// </summary>
        [JsonPropertyName("sectionReference")]
        public EdFiSectionReference SectionReference { get; set; }

        /// <summary>
        /// Gets or Sets StudentReference
        /// </summary>
        [JsonPropertyName("studentReference")]
        public EdFiStudentReference StudentReference { get; set; }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of AttemptStatusDescriptor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AttemptStatusDescriptorOption { get; private set; }

        /// <summary>
        /// An indication of the student&#39;s completion status for the section.
        /// </summary>
        /// <value>An indication of the student&#39;s completion status for the section.</value>
        [JsonPropertyName("attemptStatusDescriptor")]
        public string? AttemptStatusDescriptor { get { return this.AttemptStatusDescriptorOption; } set { this.AttemptStatusDescriptorOption = new(value); } }

        /// <summary>
        /// Used to track the state of EndDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> EndDateOption { get; private set; }

        /// <summary>
        /// Month, day, and year of the withdrawal or exit of the Student from the Section.
        /// </summary>
        /// <value>Month, day, and year of the withdrawal or exit of the Student from the Section.</value>
        [JsonPropertyName("endDate")]
        public DateOnly? EndDate { get { return this.EndDateOption; } set { this.EndDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of HomeroomIndicator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> HomeroomIndicatorOption { get; private set; }

        /// <summary>
        /// Indicates the Section is the student&#39;s homeroom. Homeroom period may the convention for taking daily attendance.
        /// </summary>
        /// <value>Indicates the Section is the student&#39;s homeroom. Homeroom period may the convention for taking daily attendance.</value>
        [JsonPropertyName("homeroomIndicator")]
        public bool? HomeroomIndicator { get { return this.HomeroomIndicatorOption; } set { this.HomeroomIndicatorOption = new(value); } }

        /// <summary>
        /// Used to track the state of RepeatIdentifierDescriptor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RepeatIdentifierDescriptorOption { get; private set; }

        /// <summary>
        /// An indication as to whether a student has previously taken a given course.        Repeated, counted in grade point average        Repeated, not counted in grade point average        Not repeated        Other.
        /// </summary>
        /// <value>An indication as to whether a student has previously taken a given course.        Repeated, counted in grade point average        Repeated, not counted in grade point average        Not repeated        Other.</value>
        [JsonPropertyName("repeatIdentifierDescriptor")]
        public string? RepeatIdentifierDescriptor { get { return this.RepeatIdentifierDescriptorOption; } set { this.RepeatIdentifierDescriptorOption = new(value); } }

        /// <summary>
        /// Used to track the state of TeacherStudentDataLinkExclusion
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> TeacherStudentDataLinkExclusionOption { get; private set; }

        /// <summary>
        /// Indicates that the student-section combination is excluded from calculation of value-added or growth attribution calculations used for a particular teacher evaluation.
        /// </summary>
        /// <value>Indicates that the student-section combination is excluded from calculation of value-added or growth attribution calculations used for a particular teacher evaluation.</value>
        [JsonPropertyName("teacherStudentDataLinkExclusion")]
        public bool? TeacherStudentDataLinkExclusion { get { return this.TeacherStudentDataLinkExclusionOption; } set { this.TeacherStudentDataLinkExclusionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Etag
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EtagOption { get; private set; }

        /// <summary>
        /// A unique system-generated value that identifies the version of the resource.
        /// </summary>
        /// <value>A unique system-generated value that identifies the version of the resource.</value>
        [JsonPropertyName("_etag")]
        public string? Etag { get { return this.EtagOption; } set { this.EtagOption = new(value); } }

        /// <summary>
        /// Used to track the state of Ext
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> ExtOption { get; private set; }

        /// <summary>
        /// Extensions to the StudentSectionAssociation entity.
        /// </summary>
        /// <value>Extensions to the StudentSectionAssociation entity.</value>
        [JsonPropertyName("_ext")]
        public Object? Ext { get { return this.ExtOption; } set { this.ExtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiStudentSectionAssociation {\n");
            sb.Append("  BeginDate: ").Append(BeginDate).Append("\n");
            sb.Append("  SectionReference: ").Append(SectionReference).Append("\n");
            sb.Append("  StudentReference: ").Append(StudentReference).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  AttemptStatusDescriptor: ").Append(AttemptStatusDescriptor).Append("\n");
            sb.Append("  EndDate: ").Append(EndDate).Append("\n");
            sb.Append("  HomeroomIndicator: ").Append(HomeroomIndicator).Append("\n");
            sb.Append("  RepeatIdentifierDescriptor: ").Append(RepeatIdentifierDescriptor).Append("\n");
            sb.Append("  TeacherStudentDataLinkExclusion: ").Append(TeacherStudentDataLinkExclusion).Append("\n");
            sb.Append("  Etag: ").Append(Etag).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // AttemptStatusDescriptor (string) maxLength
            if (this.AttemptStatusDescriptor != null && this.AttemptStatusDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for AttemptStatusDescriptor, length must be less than 306.", new [] { "AttemptStatusDescriptor" });
            }

            // RepeatIdentifierDescriptor (string) maxLength
            if (this.RepeatIdentifierDescriptor != null && this.RepeatIdentifierDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for RepeatIdentifierDescriptor, length must be less than 306.", new [] { "RepeatIdentifierDescriptor" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdFiStudentSectionAssociation" />
    /// </summary>
    public class EdFiStudentSectionAssociationJsonConverter : JsonConverter<EdFiStudentSectionAssociation>
    {
        /// <summary>
        /// The format to use to serialize BeginDate
        /// </summary>
        public static string BeginDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize EndDate
        /// </summary>
        public static string EndDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="EdFiStudentSectionAssociation" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdFiStudentSectionAssociation Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DateOnly?> beginDate = default;
            Option<EdFiSectionReference?> sectionReference = default;
            Option<EdFiStudentReference?> studentReference = default;
            Option<string?> id = default;
            Option<string?> attemptStatusDescriptor = default;
            Option<DateOnly?> endDate = default;
            Option<bool?> homeroomIndicator = default;
            Option<string?> repeatIdentifierDescriptor = default;
            Option<bool?> teacherStudentDataLinkExclusion = default;
            Option<string?> etag = default;
            Option<Object?> ext = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "beginDate":
                            beginDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "sectionReference":
                            sectionReference = new Option<EdFiSectionReference?>(JsonSerializer.Deserialize<EdFiSectionReference>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "studentReference":
                            studentReference = new Option<EdFiStudentReference?>(JsonSerializer.Deserialize<EdFiStudentReference>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "attemptStatusDescriptor":
                            attemptStatusDescriptor = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "endDate":
                            endDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "homeroomIndicator":
                            homeroomIndicator = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "repeatIdentifierDescriptor":
                            repeatIdentifierDescriptor = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "teacherStudentDataLinkExclusion":
                            teacherStudentDataLinkExclusion = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "_etag":
                            etag = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "_ext":
                            ext = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!beginDate.IsSet)
                throw new ArgumentException("Property is required for class EdFiStudentSectionAssociation.", nameof(beginDate));

            if (!sectionReference.IsSet)
                throw new ArgumentException("Property is required for class EdFiStudentSectionAssociation.", nameof(sectionReference));

            if (!studentReference.IsSet)
                throw new ArgumentException("Property is required for class EdFiStudentSectionAssociation.", nameof(studentReference));

            if (beginDate.IsSet && beginDate.Value == null)
                throw new ArgumentNullException(nameof(beginDate), "Property is not nullable for class EdFiStudentSectionAssociation.");

            if (sectionReference.IsSet && sectionReference.Value == null)
                throw new ArgumentNullException(nameof(sectionReference), "Property is not nullable for class EdFiStudentSectionAssociation.");

            if (studentReference.IsSet && studentReference.Value == null)
                throw new ArgumentNullException(nameof(studentReference), "Property is not nullable for class EdFiStudentSectionAssociation.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class EdFiStudentSectionAssociation.");

            if (attemptStatusDescriptor.IsSet && attemptStatusDescriptor.Value == null)
                throw new ArgumentNullException(nameof(attemptStatusDescriptor), "Property is not nullable for class EdFiStudentSectionAssociation.");

            if (endDate.IsSet && endDate.Value == null)
                throw new ArgumentNullException(nameof(endDate), "Property is not nullable for class EdFiStudentSectionAssociation.");

            if (homeroomIndicator.IsSet && homeroomIndicator.Value == null)
                throw new ArgumentNullException(nameof(homeroomIndicator), "Property is not nullable for class EdFiStudentSectionAssociation.");

            if (repeatIdentifierDescriptor.IsSet && repeatIdentifierDescriptor.Value == null)
                throw new ArgumentNullException(nameof(repeatIdentifierDescriptor), "Property is not nullable for class EdFiStudentSectionAssociation.");

            if (teacherStudentDataLinkExclusion.IsSet && teacherStudentDataLinkExclusion.Value == null)
                throw new ArgumentNullException(nameof(teacherStudentDataLinkExclusion), "Property is not nullable for class EdFiStudentSectionAssociation.");

            if (etag.IsSet && etag.Value == null)
                throw new ArgumentNullException(nameof(etag), "Property is not nullable for class EdFiStudentSectionAssociation.");

            if (ext.IsSet && ext.Value == null)
                throw new ArgumentNullException(nameof(ext), "Property is not nullable for class EdFiStudentSectionAssociation.");

            return new EdFiStudentSectionAssociation(beginDate.Value!.Value!, sectionReference.Value!, studentReference.Value!, id, attemptStatusDescriptor, endDate, homeroomIndicator, repeatIdentifierDescriptor, teacherStudentDataLinkExclusion, etag, ext);
        }

        /// <summary>
        /// Serializes a <see cref="EdFiStudentSectionAssociation" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiStudentSectionAssociation"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdFiStudentSectionAssociation edFiStudentSectionAssociation, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edFiStudentSectionAssociation, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdFiStudentSectionAssociation" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edFiStudentSectionAssociation"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdFiStudentSectionAssociation edFiStudentSectionAssociation, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edFiStudentSectionAssociation.SectionReference == null)
                throw new ArgumentNullException(nameof(edFiStudentSectionAssociation.SectionReference), "Property is required for class EdFiStudentSectionAssociation.");

            if (edFiStudentSectionAssociation.StudentReference == null)
                throw new ArgumentNullException(nameof(edFiStudentSectionAssociation.StudentReference), "Property is required for class EdFiStudentSectionAssociation.");

            if (edFiStudentSectionAssociation.IdOption.IsSet && edFiStudentSectionAssociation.Id == null)
                throw new ArgumentNullException(nameof(edFiStudentSectionAssociation.Id), "Property is required for class EdFiStudentSectionAssociation.");

            if (edFiStudentSectionAssociation.AttemptStatusDescriptorOption.IsSet && edFiStudentSectionAssociation.AttemptStatusDescriptor == null)
                throw new ArgumentNullException(nameof(edFiStudentSectionAssociation.AttemptStatusDescriptor), "Property is required for class EdFiStudentSectionAssociation.");

            if (edFiStudentSectionAssociation.RepeatIdentifierDescriptorOption.IsSet && edFiStudentSectionAssociation.RepeatIdentifierDescriptor == null)
                throw new ArgumentNullException(nameof(edFiStudentSectionAssociation.RepeatIdentifierDescriptor), "Property is required for class EdFiStudentSectionAssociation.");

            if (edFiStudentSectionAssociation.EtagOption.IsSet && edFiStudentSectionAssociation.Etag == null)
                throw new ArgumentNullException(nameof(edFiStudentSectionAssociation.Etag), "Property is required for class EdFiStudentSectionAssociation.");

            if (edFiStudentSectionAssociation.ExtOption.IsSet && edFiStudentSectionAssociation.Ext == null)
                throw new ArgumentNullException(nameof(edFiStudentSectionAssociation.Ext), "Property is required for class EdFiStudentSectionAssociation.");

            writer.WriteString("beginDate", edFiStudentSectionAssociation.BeginDate.ToString(BeginDateFormat));

            writer.WritePropertyName("sectionReference");
            JsonSerializer.Serialize(writer, edFiStudentSectionAssociation.SectionReference, jsonSerializerOptions);
            writer.WritePropertyName("studentReference");
            JsonSerializer.Serialize(writer, edFiStudentSectionAssociation.StudentReference, jsonSerializerOptions);
            if (edFiStudentSectionAssociation.IdOption.IsSet)
                writer.WriteString("id", edFiStudentSectionAssociation.Id);

            if (edFiStudentSectionAssociation.AttemptStatusDescriptorOption.IsSet)
                writer.WriteString("attemptStatusDescriptor", edFiStudentSectionAssociation.AttemptStatusDescriptor);

            if (edFiStudentSectionAssociation.EndDateOption.IsSet)
                writer.WriteString("endDate", edFiStudentSectionAssociation.EndDateOption.Value!.Value.ToString(EndDateFormat));

            if (edFiStudentSectionAssociation.HomeroomIndicatorOption.IsSet)
                writer.WriteBoolean("homeroomIndicator", edFiStudentSectionAssociation.HomeroomIndicatorOption.Value!.Value);

            if (edFiStudentSectionAssociation.RepeatIdentifierDescriptorOption.IsSet)
                writer.WriteString("repeatIdentifierDescriptor", edFiStudentSectionAssociation.RepeatIdentifierDescriptor);

            if (edFiStudentSectionAssociation.TeacherStudentDataLinkExclusionOption.IsSet)
                writer.WriteBoolean("teacherStudentDataLinkExclusion", edFiStudentSectionAssociation.TeacherStudentDataLinkExclusionOption.Value!.Value);

            if (edFiStudentSectionAssociation.EtagOption.IsSet)
                writer.WriteString("_etag", edFiStudentSectionAssociation.Etag);

            if (edFiStudentSectionAssociation.ExtOption.IsSet)
            {
                writer.WritePropertyName("_ext");
                JsonSerializer.Serialize(writer, edFiStudentSectionAssociation.Ext, jsonSerializerOptions);
            }
        }
    }
}
