/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.OdsApi.Sdk.v54.Client.OpenAPIDateConverter;

namespace EdFi.OdsApi.Sdk.v54.Models.All
{
    /// <summary>
    /// EdFiGradebookEntry
    /// </summary>
    [DataContract(Name = "edFi_gradebookEntry")]
    public partial class EdFiGradebookEntry : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiGradebookEntry" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdFiGradebookEntry() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiGradebookEntry" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="dateAssigned">The date the assignment, homework, or assessment was assigned or executed. (required).</param>
        /// <param name="gradebookEntryTitle">The name or title of the activity to be recorded in the GradebookEntry. (required).</param>
        /// <param name="gradingPeriodReference">gradingPeriodReference.</param>
        /// <param name="sectionReference">sectionReference (required).</param>
        /// <param name="description">A description of the assignment, homework, or classroom assessment..</param>
        /// <param name="dueDate">The date the assignment, homework, or assessment is due..</param>
        /// <param name="gradebookEntryTypeDescriptor">The type of the GradebookEntry; for example, homework, assignment, quiz, unit test, oral presentation, etc..</param>
        /// <param name="learningObjectives">An unordered collection of gradebookEntryLearningObjectives. LearningObjectives associated with the GradebookEntry..</param>
        /// <param name="learningStandards">An unordered collection of gradebookEntryLearningStandards. LearningStandard(s) associated with the GradebookEntry..</param>
        /// <param name="etag">A unique system-generated value that identifies the version of the resource..</param>
        /// <param name="ext">Extensions to the GradebookEntry entity..</param>
        public EdFiGradebookEntry(string id = default, DateOnly dateAssigned = default, string gradebookEntryTitle = default, EdFiGradingPeriodReference gradingPeriodReference = default, EdFiSectionReference sectionReference = default, string description = default, DateOnly dueDate = default, string gradebookEntryTypeDescriptor = default, List<EdFiGradebookEntryLearningObjective> learningObjectives = default, List<EdFiGradebookEntryLearningStandard> learningStandards = default, string etag = default, Object ext = default)
        {
            this.DateAssigned = dateAssigned;
            // to ensure "gradebookEntryTitle" is required (not null)
            if (gradebookEntryTitle == null)
            {
                throw new ArgumentNullException("gradebookEntryTitle is a required property for EdFiGradebookEntry and cannot be null");
            }
            this.GradebookEntryTitle = gradebookEntryTitle;
            // to ensure "sectionReference" is required (not null)
            if (sectionReference == null)
            {
                throw new ArgumentNullException("sectionReference is a required property for EdFiGradebookEntry and cannot be null");
            }
            this.SectionReference = sectionReference;
            this.Id = id;
            this.GradingPeriodReference = gradingPeriodReference;
            this.Description = description;
            this.DueDate = dueDate;
            this.GradebookEntryTypeDescriptor = gradebookEntryTypeDescriptor;
            this.LearningObjectives = learningObjectives;
            this.LearningStandards = learningStandards;
            this.Etag = etag;
            this.Ext = ext;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// The date the assignment, homework, or assessment was assigned or executed.
        /// </summary>
        /// <value>The date the assignment, homework, or assessment was assigned or executed.</value>
        [DataMember(Name = "dateAssigned", IsRequired = true, EmitDefaultValue = true)]
        public DateOnly DateAssigned { get; set; }

        /// <summary>
        /// The name or title of the activity to be recorded in the GradebookEntry.
        /// </summary>
        /// <value>The name or title of the activity to be recorded in the GradebookEntry.</value>
        [DataMember(Name = "gradebookEntryTitle", IsRequired = true, EmitDefaultValue = true)]
        public string GradebookEntryTitle { get; set; }

        /// <summary>
        /// Gets or Sets GradingPeriodReference
        /// </summary>
        [DataMember(Name = "gradingPeriodReference", EmitDefaultValue = false)]
        public EdFiGradingPeriodReference GradingPeriodReference { get; set; }

        /// <summary>
        /// Gets or Sets SectionReference
        /// </summary>
        [DataMember(Name = "sectionReference", IsRequired = true, EmitDefaultValue = true)]
        public EdFiSectionReference SectionReference { get; set; }

        /// <summary>
        /// A description of the assignment, homework, or classroom assessment.
        /// </summary>
        /// <value>A description of the assignment, homework, or classroom assessment.</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// The date the assignment, homework, or assessment is due.
        /// </summary>
        /// <value>The date the assignment, homework, or assessment is due.</value>
        [DataMember(Name = "dueDate", EmitDefaultValue = false)]
        public DateOnly DueDate { get; set; }

        /// <summary>
        /// The type of the GradebookEntry; for example, homework, assignment, quiz, unit test, oral presentation, etc.
        /// </summary>
        /// <value>The type of the GradebookEntry; for example, homework, assignment, quiz, unit test, oral presentation, etc.</value>
        [DataMember(Name = "gradebookEntryTypeDescriptor", EmitDefaultValue = false)]
        public string GradebookEntryTypeDescriptor { get; set; }

        /// <summary>
        /// An unordered collection of gradebookEntryLearningObjectives. LearningObjectives associated with the GradebookEntry.
        /// </summary>
        /// <value>An unordered collection of gradebookEntryLearningObjectives. LearningObjectives associated with the GradebookEntry.</value>
        [DataMember(Name = "learningObjectives", EmitDefaultValue = false)]
        public List<EdFiGradebookEntryLearningObjective> LearningObjectives { get; set; }

        /// <summary>
        /// An unordered collection of gradebookEntryLearningStandards. LearningStandard(s) associated with the GradebookEntry.
        /// </summary>
        /// <value>An unordered collection of gradebookEntryLearningStandards. LearningStandard(s) associated with the GradebookEntry.</value>
        [DataMember(Name = "learningStandards", EmitDefaultValue = false)]
        public List<EdFiGradebookEntryLearningStandard> LearningStandards { get; set; }

        /// <summary>
        /// A unique system-generated value that identifies the version of the resource.
        /// </summary>
        /// <value>A unique system-generated value that identifies the version of the resource.</value>
        [DataMember(Name = "_etag", EmitDefaultValue = false)]
        public string Etag { get; set; }

        /// <summary>
        /// Extensions to the GradebookEntry entity.
        /// </summary>
        /// <value>Extensions to the GradebookEntry entity.</value>
        [DataMember(Name = "_ext", EmitDefaultValue = false)]
        public Object Ext { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdFiGradebookEntry {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  DateAssigned: ").Append(DateAssigned).Append("\n");
            sb.Append("  GradebookEntryTitle: ").Append(GradebookEntryTitle).Append("\n");
            sb.Append("  GradingPeriodReference: ").Append(GradingPeriodReference).Append("\n");
            sb.Append("  SectionReference: ").Append(SectionReference).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  DueDate: ").Append(DueDate).Append("\n");
            sb.Append("  GradebookEntryTypeDescriptor: ").Append(GradebookEntryTypeDescriptor).Append("\n");
            sb.Append("  LearningObjectives: ").Append(LearningObjectives).Append("\n");
            sb.Append("  LearningStandards: ").Append(LearningStandards).Append("\n");
            sb.Append("  Etag: ").Append(Etag).Append("\n");
            sb.Append("  Ext: ").Append(Ext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // GradebookEntryTitle (string) maxLength
            if (this.GradebookEntryTitle != null && this.GradebookEntryTitle.Length > 60)
            {
                yield return new ValidationResult("Invalid value for GradebookEntryTitle, length must be less than 60.", new [] { "GradebookEntryTitle" });
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 1024)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 1024.", new [] { "Description" });
            }

            // GradebookEntryTypeDescriptor (string) maxLength
            if (this.GradebookEntryTypeDescriptor != null && this.GradebookEntryTypeDescriptor.Length > 306)
            {
                yield return new ValidationResult("Invalid value for GradebookEntryTypeDescriptor, length must be less than 306.", new [] { "GradebookEntryTypeDescriptor" });
            }

            yield break;
        }
    }

}
